### ISSUE TITLE
Migrate all variables to PEP-008 compliant names

### ISSUE THREAD

**Issue by Serverlag** [Serverlag/router-config-generator#15]
Based on https://www.python.org/dev/peps/pep-0008/ (Function and Variable Names) migrate to using correct style for Python variable names.

**Comment by jamesditrapani** [comment]
Hi @Serverlag, any ETA on PR to fix #15?

**Comment by patoh** [comment]
@Serverlag - when will this get implemented? This is holding us back from using router-config-generator
